'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace SoapCancelar
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Timbrado Remoto de INIBinding", [Namespace]:="urn:wservicewsdl")>  _
    Partial Public Class TimbradoRemotodeINI
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private timbrarini1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private timbrarini2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CAJAS.My.MySettings.Default.CAJAs_SoapCancelar_Timbrado_Remoto_de_INI
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event timbrarini1Completed As timbrarini1CompletedEventHandler
        
        '''<remarks/>
        Public Event timbrarini2Completed As timbrarini2CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#timbrarini1", RequestNamespace:="urn:wservicewsdl", ResponseNamespace:="urn:wservicewsdl")>  _
        Public Function timbrarini1(ByVal rfc As String, ByVal inib64 As String, ByVal cer As String, ByVal key As String, ByVal pass As String) As <System.Xml.Serialization.SoapElementAttribute("return")> RespuestaWS
            Dim results() As Object = Me.Invoke("timbrarini1", New Object() {rfc, inib64, cer, key, pass})
            Return CType(results(0),RespuestaWS)
        End Function
        
        '''<remarks/>
        Public Overloads Sub timbrarini1Async(ByVal rfc As String, ByVal inib64 As String, ByVal cer As String, ByVal key As String, ByVal pass As String)
            Me.timbrarini1Async(rfc, inib64, cer, key, pass, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub timbrarini1Async(ByVal rfc As String, ByVal inib64 As String, ByVal cer As String, ByVal key As String, ByVal pass As String, ByVal userState As Object)
            If (Me.timbrarini1OperationCompleted Is Nothing) Then
                Me.timbrarini1OperationCompleted = AddressOf Me.Ontimbrarini1OperationCompleted
            End If
            Me.InvokeAsync("timbrarini1", New Object() {rfc, inib64, cer, key, pass}, Me.timbrarini1OperationCompleted, userState)
        End Sub
        
        Private Sub Ontimbrarini1OperationCompleted(ByVal arg As Object)
            If (Not (Me.timbrarini1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent timbrarini1Completed(Me, New timbrarini1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#timbrarini2", RequestNamespace:="urn:wservicewsdl", ResponseNamespace:="urn:wservicewsdl")>  _
        Public Function timbrarini2(ByVal rfc As String, ByVal inib64 As String, ByVal cer As String, ByVal key As String, ByVal pass As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("timbrarini2", New Object() {rfc, inib64, cer, key, pass})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub timbrarini2Async(ByVal rfc As String, ByVal inib64 As String, ByVal cer As String, ByVal key As String, ByVal pass As String)
            Me.timbrarini2Async(rfc, inib64, cer, key, pass, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub timbrarini2Async(ByVal rfc As String, ByVal inib64 As String, ByVal cer As String, ByVal key As String, ByVal pass As String, ByVal userState As Object)
            If (Me.timbrarini2OperationCompleted Is Nothing) Then
                Me.timbrarini2OperationCompleted = AddressOf Me.Ontimbrarini2OperationCompleted
            End If
            Me.InvokeAsync("timbrarini2", New Object() {rfc, inib64, cer, key, pass}, Me.timbrarini2OperationCompleted, userState)
        End Sub
        
        Private Sub Ontimbrarini2OperationCompleted(ByVal arg As Object)
            If (Not (Me.timbrarini2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent timbrarini2Completed(Me, New timbrarini2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:wservicewsdl")>  _
    Partial Public Class RespuestaWS
        
        Private cfdiField As String
        
        Private pngField As String
        
        Private idpacField As Integer
        
        Private pacField As Integer
        
        Private produccionField As String
        
        Private codigo_mf_numeroField As Integer
        
        Private codigo_mf_textoField As String
        
        Private mensaje_original_pac_jsonField As String
        
        Private canceladaField As String
        
        Private saldoField As Integer
        
        Private uuidField As String
        
        Private servidorField As String
        
        Private representacion_impresa_cadenaField As String
        
        Private representacion_impresa_certificado_noField As String
        
        Private representacion_impresa_fecha_timbradoField As String
        
        Private representacion_impresa_selloField As String
        
        Private representacion_impresa_selloSATField As String
        
        Private representacion_impresa_certificadoSATField As String
        
        Private debugField As String
        
        '''<remarks/>
        Public Property cfdi() As String
            Get
                Return Me.cfdiField
            End Get
            Set
                Me.cfdiField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property png() As String
            Get
                Return Me.pngField
            End Get
            Set
                Me.pngField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idpac() As Integer
            Get
                Return Me.idpacField
            End Get
            Set
                Me.idpacField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property pac() As Integer
            Get
                Return Me.pacField
            End Get
            Set
                Me.pacField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property produccion() As String
            Get
                Return Me.produccionField
            End Get
            Set
                Me.produccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigo_mf_numero() As Integer
            Get
                Return Me.codigo_mf_numeroField
            End Get
            Set
                Me.codigo_mf_numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigo_mf_texto() As String
            Get
                Return Me.codigo_mf_textoField
            End Get
            Set
                Me.codigo_mf_textoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensaje_original_pac_json() As String
            Get
                Return Me.mensaje_original_pac_jsonField
            End Get
            Set
                Me.mensaje_original_pac_jsonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cancelada() As String
            Get
                Return Me.canceladaField
            End Get
            Set
                Me.canceladaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property saldo() As Integer
            Get
                Return Me.saldoField
            End Get
            Set
                Me.saldoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property servidor() As String
            Get
                Return Me.servidorField
            End Get
            Set
                Me.servidorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property representacion_impresa_cadena() As String
            Get
                Return Me.representacion_impresa_cadenaField
            End Get
            Set
                Me.representacion_impresa_cadenaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property representacion_impresa_certificado_no() As String
            Get
                Return Me.representacion_impresa_certificado_noField
            End Get
            Set
                Me.representacion_impresa_certificado_noField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property representacion_impresa_fecha_timbrado() As String
            Get
                Return Me.representacion_impresa_fecha_timbradoField
            End Get
            Set
                Me.representacion_impresa_fecha_timbradoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property representacion_impresa_sello() As String
            Get
                Return Me.representacion_impresa_selloField
            End Get
            Set
                Me.representacion_impresa_selloField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property representacion_impresa_selloSAT() As String
            Get
                Return Me.representacion_impresa_selloSATField
            End Get
            Set
                Me.representacion_impresa_selloSATField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property representacion_impresa_certificadoSAT() As String
            Get
                Return Me.representacion_impresa_certificadoSATField
            End Get
            Set
                Me.representacion_impresa_certificadoSATField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property debug() As String
            Get
                Return Me.debugField
            End Get
            Set
                Me.debugField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub timbrarini1CompletedEventHandler(ByVal sender As Object, ByVal e As timbrarini1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class timbrarini1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaWS
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaWS)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub timbrarini2CompletedEventHandler(ByVal sender As Object, ByVal e As timbrarini2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class timbrarini2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
