'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WSCancelarFactura40
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Cancelar cfdi 4.0 SATBinding", [Namespace]:="urn:wservicewsdl")>  _
    Partial Public Class Cancelarcfdi40SAT
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private cancelarCfdiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private aceptarCancelarCfdiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private rechazarCancelarCfdiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarCancelarCfdiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarCfdiRelacionadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CAJAS.My.MySettings.Default.CAJAs_WSCancelarFactura40_Cancelar_cfdi_4_0_SAT
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event cancelarCfdiCompleted As cancelarCfdiCompletedEventHandler
        
        '''<remarks/>
        Public Event aceptarCancelarCfdiCompleted As aceptarCancelarCfdiCompletedEventHandler
        
        '''<remarks/>
        Public Event rechazarCancelarCfdiCompleted As rechazarCancelarCfdiCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarCancelarCfdiCompleted As consultarCancelarCfdiCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarCfdiRelacionadoCompleted As consultarCfdiRelacionadoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#cancelarCfdi", RequestNamespace:="urn:wservicewsdl", ResponseNamespace:="urn:wservicewsdl")>  _
        Public Function cancelarCfdi(ByVal datos As datos) As <System.Xml.Serialization.SoapElementAttribute("return")> respuesta
            Dim results() As Object = Me.Invoke("cancelarCfdi", New Object() {datos})
            Return CType(results(0),respuesta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cancelarCfdiAsync(ByVal datos As datos)
            Me.cancelarCfdiAsync(datos, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cancelarCfdiAsync(ByVal datos As datos, ByVal userState As Object)
            If (Me.cancelarCfdiOperationCompleted Is Nothing) Then
                Me.cancelarCfdiOperationCompleted = AddressOf Me.OncancelarCfdiOperationCompleted
            End If
            Me.InvokeAsync("cancelarCfdi", New Object() {datos}, Me.cancelarCfdiOperationCompleted, userState)
        End Sub
        
        Private Sub OncancelarCfdiOperationCompleted(ByVal arg As Object)
            If (Not (Me.cancelarCfdiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cancelarCfdiCompleted(Me, New cancelarCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#aceptarCancelarCfdi", RequestNamespace:="urn:wservicewsdl", ResponseNamespace:="urn:wservicewsdl")>  _
        Public Function aceptarCancelarCfdi(ByVal datos As datos) As <System.Xml.Serialization.SoapElementAttribute("return")> respuesta
            Dim results() As Object = Me.Invoke("aceptarCancelarCfdi", New Object() {datos})
            Return CType(results(0),respuesta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub aceptarCancelarCfdiAsync(ByVal datos As datos)
            Me.aceptarCancelarCfdiAsync(datos, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub aceptarCancelarCfdiAsync(ByVal datos As datos, ByVal userState As Object)
            If (Me.aceptarCancelarCfdiOperationCompleted Is Nothing) Then
                Me.aceptarCancelarCfdiOperationCompleted = AddressOf Me.OnaceptarCancelarCfdiOperationCompleted
            End If
            Me.InvokeAsync("aceptarCancelarCfdi", New Object() {datos}, Me.aceptarCancelarCfdiOperationCompleted, userState)
        End Sub
        
        Private Sub OnaceptarCancelarCfdiOperationCompleted(ByVal arg As Object)
            If (Not (Me.aceptarCancelarCfdiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent aceptarCancelarCfdiCompleted(Me, New aceptarCancelarCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#rechazarCancelarCfdi", RequestNamespace:="urn:wservicewsdl", ResponseNamespace:="urn:wservicewsdl")>  _
        Public Function rechazarCancelarCfdi(ByVal datos As datos) As <System.Xml.Serialization.SoapElementAttribute("return")> respuesta
            Dim results() As Object = Me.Invoke("rechazarCancelarCfdi", New Object() {datos})
            Return CType(results(0),respuesta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub rechazarCancelarCfdiAsync(ByVal datos As datos)
            Me.rechazarCancelarCfdiAsync(datos, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub rechazarCancelarCfdiAsync(ByVal datos As datos, ByVal userState As Object)
            If (Me.rechazarCancelarCfdiOperationCompleted Is Nothing) Then
                Me.rechazarCancelarCfdiOperationCompleted = AddressOf Me.OnrechazarCancelarCfdiOperationCompleted
            End If
            Me.InvokeAsync("rechazarCancelarCfdi", New Object() {datos}, Me.rechazarCancelarCfdiOperationCompleted, userState)
        End Sub
        
        Private Sub OnrechazarCancelarCfdiOperationCompleted(ByVal arg As Object)
            If (Not (Me.rechazarCancelarCfdiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent rechazarCancelarCfdiCompleted(Me, New rechazarCancelarCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#consultarCancelarCfdi", RequestNamespace:="urn:wservicewsdl", ResponseNamespace:="urn:wservicewsdl")>  _
        Public Function consultarCancelarCfdi(ByVal datos As datos) As <System.Xml.Serialization.SoapElementAttribute("return")> respuestaCCancelar
            Dim results() As Object = Me.Invoke("consultarCancelarCfdi", New Object() {datos})
            Return CType(results(0),respuestaCCancelar)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarCancelarCfdiAsync(ByVal datos As datos)
            Me.consultarCancelarCfdiAsync(datos, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarCancelarCfdiAsync(ByVal datos As datos, ByVal userState As Object)
            If (Me.consultarCancelarCfdiOperationCompleted Is Nothing) Then
                Me.consultarCancelarCfdiOperationCompleted = AddressOf Me.OnconsultarCancelarCfdiOperationCompleted
            End If
            Me.InvokeAsync("consultarCancelarCfdi", New Object() {datos}, Me.consultarCancelarCfdiOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarCancelarCfdiOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarCancelarCfdiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarCancelarCfdiCompleted(Me, New consultarCancelarCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#consultarCfdiRelacionado", RequestNamespace:="urn:wservicewsdl", ResponseNamespace:="urn:wservicewsdl")>  _
        Public Function consultarCfdiRelacionado(ByVal datos As datosRelacionados) As <System.Xml.Serialization.SoapElementAttribute("return")> respuesta
            Dim results() As Object = Me.Invoke("consultarCfdiRelacionado", New Object() {datos})
            Return CType(results(0),respuesta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarCfdiRelacionadoAsync(ByVal datos As datosRelacionados)
            Me.consultarCfdiRelacionadoAsync(datos, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarCfdiRelacionadoAsync(ByVal datos As datosRelacionados, ByVal userState As Object)
            If (Me.consultarCfdiRelacionadoOperationCompleted Is Nothing) Then
                Me.consultarCfdiRelacionadoOperationCompleted = AddressOf Me.OnconsultarCfdiRelacionadoOperationCompleted
            End If
            Me.InvokeAsync("consultarCfdiRelacionado", New Object() {datos}, Me.consultarCfdiRelacionadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarCfdiRelacionadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarCfdiRelacionadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarCfdiRelacionadoCompleted(Me, New consultarCfdiRelacionadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:wservicewsdl")>  _
    Partial Public Class datos
        
        Private usuarioField As String
        
        Private passField As String
        
        Private accionField As String
        
        Private produccionField As String
        
        Private uuidField As String
        
        Private rfcField As String
        
        Private passwordField As String
        
        Private motivoField As String
        
        Private folioSustitucionField As String
        
        Private b64CerField As String
        
        Private b64KeyField As String
        
        '''<remarks/>
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property pass() As String
            Get
                Return Me.passField
            End Get
            Set
                Me.passField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property accion() As String
            Get
                Return Me.accionField
            End Get
            Set
                Me.accionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property produccion() As String
            Get
                Return Me.produccionField
            End Get
            Set
                Me.produccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rfc() As String
            Get
                Return Me.rfcField
            End Get
            Set
                Me.rfcField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property motivo() As String
            Get
                Return Me.motivoField
            End Get
            Set
                Me.motivoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property folioSustitucion() As String
            Get
                Return Me.folioSustitucionField
            End Get
            Set
                Me.folioSustitucionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property b64Cer() As String
            Get
                Return Me.b64CerField
            End Get
            Set
                Me.b64CerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property b64Key() As String
            Get
                Return Me.b64KeyField
            End Get
            Set
                Me.b64KeyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:wservicewsdl")>  _
    Partial Public Class datosRelacionados
        
        Private usuarioField As String
        
        Private passField As String
        
        Private accionField As String
        
        Private produccionField As String
        
        Private uuidField As String
        
        Private rfc_receptorField As String
        
        Private passwordField As String
        
        Private b64Cer_receptorField As String
        
        Private b64Key_receptorField As String
        
        '''<remarks/>
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property pass() As String
            Get
                Return Me.passField
            End Get
            Set
                Me.passField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property accion() As String
            Get
                Return Me.accionField
            End Get
            Set
                Me.accionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property produccion() As String
            Get
                Return Me.produccionField
            End Get
            Set
                Me.produccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rfc_receptor() As String
            Get
                Return Me.rfc_receptorField
            End Get
            Set
                Me.rfc_receptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property b64Cer_receptor() As String
            Get
                Return Me.b64Cer_receptorField
            End Get
            Set
                Me.b64Cer_receptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property b64Key_receptor() As String
            Get
                Return Me.b64Key_receptorField
            End Get
            Set
                Me.b64Key_receptorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:wservicewsdl")>  _
    Partial Public Class respuestaCCancelar
        
        Private codigo_mf_numeroField As String
        
        Private codigo_mf_textoField As String
        
        Private mensaje_originalField As String
        
        Private statusField As String
        
        Private json_uuidsField As String
        
        Private codigo_respuesta_satField As String
        
        Private codigo_respuesta_sat_textoField As String
        
        Private codigo_respuesta_sat_texto_descripcionField As String
        
        Private produccionField As String
        
        Private accionField As String
        
        '''<remarks/>
        Public Property codigo_mf_numero() As String
            Get
                Return Me.codigo_mf_numeroField
            End Get
            Set
                Me.codigo_mf_numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigo_mf_texto() As String
            Get
                Return Me.codigo_mf_textoField
            End Get
            Set
                Me.codigo_mf_textoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensaje_original() As String
            Get
                Return Me.mensaje_originalField
            End Get
            Set
                Me.mensaje_originalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property json_uuids() As String
            Get
                Return Me.json_uuidsField
            End Get
            Set
                Me.json_uuidsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigo_respuesta_sat() As String
            Get
                Return Me.codigo_respuesta_satField
            End Get
            Set
                Me.codigo_respuesta_satField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigo_respuesta_sat_texto() As String
            Get
                Return Me.codigo_respuesta_sat_textoField
            End Get
            Set
                Me.codigo_respuesta_sat_textoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigo_respuesta_sat_texto_descripcion() As String
            Get
                Return Me.codigo_respuesta_sat_texto_descripcionField
            End Get
            Set
                Me.codigo_respuesta_sat_texto_descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property produccion() As String
            Get
                Return Me.produccionField
            End Get
            Set
                Me.produccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property accion() As String
            Get
                Return Me.accionField
            End Get
            Set
                Me.accionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:wservicewsdl")>  _
    Partial Public Class respuesta
        
        Private codigo_mf_numeroField As String
        
        Private codigo_mf_textoField As String
        
        Private mensaje_originalField As String
        
        Private acuseField As String
        
        Private statusField As String
        
        Private uuidField As String
        
        Private codigo_respuesta_satField As String
        
        Private codigo_respuesta_sat_textoField As String
        
        Private codigo_respuesta_sat_texto_descripcionField As String
        
        Private produccionField As String
        
        Private accionField As String
        
        '''<remarks/>
        Public Property codigo_mf_numero() As String
            Get
                Return Me.codigo_mf_numeroField
            End Get
            Set
                Me.codigo_mf_numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigo_mf_texto() As String
            Get
                Return Me.codigo_mf_textoField
            End Get
            Set
                Me.codigo_mf_textoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensaje_original() As String
            Get
                Return Me.mensaje_originalField
            End Get
            Set
                Me.mensaje_originalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acuse() As String
            Get
                Return Me.acuseField
            End Get
            Set
                Me.acuseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigo_respuesta_sat() As String
            Get
                Return Me.codigo_respuesta_satField
            End Get
            Set
                Me.codigo_respuesta_satField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigo_respuesta_sat_texto() As String
            Get
                Return Me.codigo_respuesta_sat_textoField
            End Get
            Set
                Me.codigo_respuesta_sat_textoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigo_respuesta_sat_texto_descripcion() As String
            Get
                Return Me.codigo_respuesta_sat_texto_descripcionField
            End Get
            Set
                Me.codigo_respuesta_sat_texto_descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property produccion() As String
            Get
                Return Me.produccionField
            End Get
            Set
                Me.produccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property accion() As String
            Get
                Return Me.accionField
            End Get
            Set
                Me.accionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub cancelarCfdiCompletedEventHandler(ByVal sender As Object, ByVal e As cancelarCfdiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cancelarCfdiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuesta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuesta)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub aceptarCancelarCfdiCompletedEventHandler(ByVal sender As Object, ByVal e As aceptarCancelarCfdiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class aceptarCancelarCfdiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuesta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuesta)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub rechazarCancelarCfdiCompletedEventHandler(ByVal sender As Object, ByVal e As rechazarCancelarCfdiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class rechazarCancelarCfdiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuesta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuesta)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub consultarCancelarCfdiCompletedEventHandler(ByVal sender As Object, ByVal e As consultarCancelarCfdiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarCancelarCfdiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaCCancelar
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaCCancelar)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub consultarCfdiRelacionadoCompletedEventHandler(ByVal sender As Object, ByVal e As consultarCfdiRelacionadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarCfdiRelacionadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuesta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuesta)
            End Get
        End Property
    End Class
End Namespace
