'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tarifa")>  _
        Public Property campotarifa() As String
            Get
                Return CType(Me("campotarifa"),String)
            End Get
            Set
                Me("campotarifa") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("pago_agua")>  _
        Public Property campoaguafija() As String
            Get
                Return CType(Me("campoaguafija"),String)
            End Get
            Set
                Me("campoaguafija") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("periodo")>  _
        Public Property campoano() As String
            Get
                Return CType(Me("campoano"),String)
            End Get
            Set
                Me("campoano") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("medido")>  _
        Public Property booleanmedido() As String
            Get
                Return CType(Me("booleanmedido"),String)
            End Get
            Set
                Me("booleanmedido") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("cuotas")>  _
        Public Property tablacuotas() As String
            Get
                Return CType(Me("tablacuotas"),String)
            End Get
            Set
                Me("tablacuotas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ALCANTARILLADO")>  _
        Public Property booleanalcantarillado() As String
            Get
                Return CType(Me("booleanalcantarillado"),String)
            End Get
            Set
                Me("booleanalcantarillado") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("IVA")>  _
        Public Property booleanIVA() As String
            Get
                Return CType(Me("booleanIVA"),String)
            End Get
            Set
                Me("booleanIVA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RECARGOS")>  _
        Public Property booleanrecargos() As String
            Get
                Return CType(Me("booleanrecargos"),String)
            End Get
            Set
                Me("booleanrecargos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("alcapcuo")>  _
        Public Property booleancobrarfijoalcantarillado() As String
            Get
                Return CType(Me("booleancobrarfijoalcantarillado"),String)
            End Get
            Set
                Me("booleancobrarfijoalcantarillado") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PorcAlca")>  _
        Public Property Porcentajedealcantarillado() As String
            Get
                Return CType(Me("Porcentajedealcantarillado"),String)
            End Get
            Set
                Me("Porcentajedealcantarillado") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("saneacuo")>  _
        Public Property booleansaneamiento() As String
            Get
                Return CType(Me("booleansaneamiento"),String)
            End Get
            Set
                Me("booleansaneamiento") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("sanepcuo")>  _
        Public Property booleancobrarfijosaneamiento() As String
            Get
                Return CType(Me("booleancobrarfijosaneamiento"),String)
            End Get
            Set
                Me("booleancobrarfijosaneamiento") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("sanecuo")>  _
        Public Property camposaneamiento() As String
            Get
                Return CType(Me("camposaneamiento"),String)
            End Get
            Set
                Me("camposaneamiento") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("porcsanea")>  _
        Public Property Porcentajedesaneamiento() As String
            Get
                Return CType(Me("Porcentajedesaneamiento"),String)
            End Get
            Set
                Me("Porcentajedesaneamiento") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PorcAlca")>  _
        Public Property campoalcantarillo() As String
            Get
                Return CType(Me("campoalcantarillo"),String)
            End Get
            Set
                Me("campoalcantarillo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CONSULTA")>  _
        Public Property tipocaja() As String
            Get
                Return CType(Me("tipocaja"),String)
            End Get
            Set
                Me("tipocaja") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property folio() As String
            Get
                Return CType(Me("folio"),String)
            End Get
            Set
                Me("folio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property caja() As String
            Get
                Return CType(Me("caja"),String)
            End Get
            Set
                Me("caja") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("F")>  _
        Public Property serie() As String
            Get
                Return CType(Me("serie"),String)
            End Get
            Set
                Me("serie") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("NO")>  _
        Public Property escajamovil() As String
            Get
                Return CType(Me("escajamovil"),String)
            End Get
            Set
                Me("escajamovil") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SI")>  _
        Public Property esAdministrativa() As String
            Get
                Return CType(Me("esAdministrativa"),String)
            End Get
            Set
                Me("esAdministrativa") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property Porcentajederecargo() As Double
            Get
                Return CType(Me("Porcentajederecargo"),Double)
            End Get
            Set
                Me("Porcentajederecargo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-4")>  _
        Public Property Clavedeconsumo() As String
            Get
                Return CType(Me("Clavedeconsumo"),String)
            End Get
            Set
                Me("Clavedeconsumo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-6")>  _
        Public Property Clavedealcantarillado() As String
            Get
                Return CType(Me("Clavedealcantarillado"),String)
            End Get
            Set
                Me("Clavedealcantarillado") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property clavedesaneamiento() As String
            Get
                Return CType(Me("clavedesaneamiento"),String)
            End Get
            Set
                Me("clavedesaneamiento") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-3")>  _
        Public Property Clavederecargo() As String
            Get
                Return CType(Me("Clavederecargo"),String)
            End Get
            Set
                Me("Clavederecargo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-26")>  _
        Public Property Clavedeiva() As String
            Get
                Return CType(Me("Clavedeiva"),String)
            End Get
            Set
                Me("Clavedeiva") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tic1")>  _
        Public Property formatorecibo() As String
            Get
                Return CType(Me("formatorecibo"),String)
            End Get
            Set
                Me("formatorecibo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-14")>  _
        Public Property ClavedeRezago() As String
            Get
                Return CType(Me("ClavedeRezago"),String)
            End Get
            Set
                Me("ClavedeRezago") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tarifa")>  _
        Public Property campousuariotarifa() As String
            Get
                Return CType(Me("campousuariotarifa"),String)
            End Get
            Set
                Me("campousuariotarifa") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SI")>  _
        Public Property TimbrarPrueba() As String
            Get
                Return CType(Me("TimbrarPrueba"),String)
            End Get
            Set
                Me("TimbrarPrueba") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property copiasderecibo() As String
            Get
                Return CType(Me("copiasderecibo"),String)
            End Get
            Set
                Me("copiasderecibo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Pwd")>  _
        Public Property Pass() As String
            Get
                Return CType(Me("Pass"),String)
            End Get
            Set
                Me("Pass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("26")>  _
        Public Property ClaveAgua() As String
            Get
                Return CType(Me("ClaveAgua"),String)
            End Get
            Set
                Me("ClaveAgua") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("NO")>  _
        Public Property GuardaCobroexpress() As String
            Get
                Return CType(Me("GuardaCobroexpress"),String)
            End Get
            Set
                Me("GuardaCobroexpress") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property TopeRecargo() As Double
            Get
                Return CType(Me("TopeRecargo"),Double)
            End Get
            Set
                Me("TopeRecargo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("NO")>  _
        Public Property imprimirhitorial() As String
            Get
                Return CType(Me("imprimirhitorial"),String)
            End Get
            Set
                Me("imprimirhitorial") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("REC2")>  _
        Public Property FormatoCopia() As String
            Get
                Return CType(Me("FormatoCopia"),String)
            End Get
            Set
                Me("FormatoCopia") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VALVUL")>  _
        Public Property clavevalvulista() As String
            Get
                Return CType(Me("clavevalvulista"),String)
            End Get
            Set
                Me("clavevalvulista") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SI")>  _
        Public Property cobrarvalvulista() As String
            Get
                Return CType(Me("cobrarvalvulista"),String)
            End Get
            Set
                Me("cobrarvalvulista") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sean estas Lineas el amable conducto para enviarte un coordial sauldo, y al mismo"& _ 
            " tiempo agradecerte por pago, anexamos la factura de tu pago."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Es un placer se"& _ 
            "rvirte"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"DEPARTAMENTO COMERCIAL")>  _
        Public Property MENSAJECORREO() As String
            Get
                Return CType(Me("MENSAJECORREO"),String)
            End Get
            Set
                Me("MENSAJECORREO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("caposafacturacion@gmail.com")>  _
        Public Property Usuariocorreo() As String
            Get
                Return CType(Me("Usuariocorreo"),String)
            End Get
            Set
                Me("Usuariocorreo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Caposa2015")>  _
        Public Property Passwordcorreo() As String
            Get
                Return CType(Me("Passwordcorreo"),String)
            End Get
            Set
                Me("Passwordcorreo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Factura Electronica C.A.P.O.S.A.")>  _
        Public Property Asuntocorreo() As String
            Get
                Return CType(Me("Asuntocorreo"),String)
            End Get
            Set
                Me("Asuntocorreo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("caposafacturacion@gmail.com")>  _
        Public Property CorreoFacturas() As String
            Get
                Return CType(Me("CorreoFacturas"),String)
            End Get
            Set
                Me("CorreoFacturas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("enviofacturas@caposa.gob.mx")>  _
        Public Property Correodefault() As String
            Get
                Return CType(Me("Correodefault"),String)
            End Get
            Set
                Me("Correodefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://fprontorojo.n5nitro.com/prometheus/ws_cancel.php")>  _
        Public ReadOnly Property CAJAS_cancelafactupronto_wsCancelacion() As String
            Get
                Return CType(Me("CAJAS_cancelafactupronto_wsCancelacion"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://fprontorojo.n5nitro.com/prometheus/txt_timbrado_factupronto.php")>  _
        Public Property direcciondepruebas() As String
            Get
                Return CType(Me("direcciondepruebas"),String)
            End Get
            Set
                Me("direcciondepruebas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.factupronto.mx/prometheus/txt_timbrado_factupronto.php")>  _
        Public Property direccionwebservice() As String
            Get
                Return CType(Me("direccionwebservice"),String)
            End Get
            Set
                Me("direccionwebservice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CAS141230736")>  _
        Public Property RFC() As String
            Get
                Return CType(Me("RFC"),String)
            End Get
            Set
                Me("RFC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("603")>  _
        Public Property Regimen() As String
            Get
                Return CType(Me("Regimen"),String)
            End Get
            Set
                Me("Regimen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CAS141230736")>  _
        Public Property UsuarioMultifacturas() As String
            Get
                Return CType(Me("UsuarioMultifacturas"),String)
            End Get
            Set
                Me("UsuarioMultifacturas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CAYSA2025")>  _
        Public Property PassFacturaMultifacturas() As String
            Get
                Return CType(Me("PassFacturaMultifacturas"),String)
            End Get
            Set
                Me("PassFacturaMultifacturas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SI"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property ProduccionMultifacturas() As String
            Get
                Return CType(Me("ProduccionMultifacturas"),String)
            End Get
            Set
                Me("ProduccionMultifacturas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\\sdk2\\certificados\\caysa.cer")>  _
        Public Property CER() As String
            Get
                Return CType(Me("CER"),String)
            End Get
            Set
                Me("CER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\\sdk2\\certificados\\caysa.key")>  _
        Public Property KEY() As String
            Get
                Return CType(Me("KEY"),String)
            End Get
            Set
                Me("KEY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CAYSA202427")>  _
        Public Property KeyContrasena() As String
            Get
                Return CType(Me("KeyContrasena"),String)
            End Get
            Set
                Me("KeyContrasena") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MULTIFACTURAS")>  _
        Public Property ProvedorFacturacion() As String
            Get
                Return CType(Me("ProvedorFacturacion"),String)
            End Get
            Set
                Me("ProvedorFacturacion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("eduardovime@outlook.com")>  _
        Public Property usuariopruebasfactupronto() As String
            Get
                Return CType(Me("usuariopruebasfactupronto"),String)
            End Get
            Set
                Me("usuariopruebasfactupronto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Kelcay74@")>  _
        Public Property passwordpruebasfactupronto() As String
            Get
                Return CType(Me("passwordpruebasfactupronto"),String)
            End Get
            Set
                Me("passwordpruebasfactupronto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("victorfalcon@caposa.gob.mx")>  _
        Public Property usuarioprodfactupronto() As String
            Get
                Return CType(Me("usuarioprodfactupronto"),String)
            End Get
            Set
                Me("usuarioprodfactupronto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Victor2014@")>  _
        Public Property passwordprodfactupronto() As String
            Get
                Return CType(Me("passwordprodfactupronto"),String)
            End Get
            Set
                Me("passwordprodfactupronto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1234567890")>  _
        Public Property cuentabancariadestino() As String
            Get
                Return CType(Me("cuentabancariadestino"),String)
            End Get
            Set
                Me("cuentabancariadestino") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BBA830831LJ2")>  _
        Public Property rfcbancodestino() As String
            Get
                Return CType(Me("rfcbancodestino"),String)
            End Get
            Set
                Me("rfcbancodestino") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Agua")>  _
        Public Property servidorreporte() As String
            Get
                Return CType(Me("servidorreporte"),String)
            End Get
            Set
                Me("servidorreporte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
        Public Property usuarioreporte() As String
            Get
                Return CType(Me("usuarioreporte"),String)
            End Get
            Set
                Me("usuarioreporte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gabriela@2018")>  _
        Public Property passreporte() As String
            Get
                Return CType(Me("passreporte"),String)
            End Get
            Set
                Me("passreporte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("agua_ajacuba")>  _
        Public Property basereporte() As String
            Get
                Return CType(Me("basereporte"),String)
            End Get
            Set
                Me("basereporte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("NO")>  _
        Public Property manejacatalogocalles() As String
            Get
                Return CType(Me("manejacatalogocalles"),String)
            End Get
            Set
                Me("manejacatalogocalles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CON001")>  _
        Public Property claveConvenio() As String
            Get
                Return CType(Me("claveConvenio"),String)
            End Get
            Set
                Me("claveConvenio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blanco")>  _
        Public Property colorfactura() As String
            Get
                Return CType(Me("colorfactura"),String)
            End Get
            Set
                Me("colorfactura") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://pac1.multifacturas.com/pac/timbrarini.php")>  _
        Public ReadOnly Property CAJAs_SoapCancelar_Timbrado_Remoto_de_INI() As String
            Get
                Return CType(Me("CAJAs_SoapCancelar_Timbrado_Remoto_de_INI"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://pac1.multifacturas.com/cancelacion2022/index.php")>  _
        Public ReadOnly Property CAJAs_WSCancelarFactura40_Cancelar_cfdi_4_0_SAT() As String
            Get
                Return CType(Me("CAJAs_WSCancelarFactura40_Cancelar_cfdi_4_0_SAT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("03")>  _
        Public Property Periodicidad() As String
            Get
                Return CType(Me("Periodicidad"),String)
            End Get
            Set
                Me("Periodicidad") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dsn=Agua")>  _
        Public ReadOnly Property baseaguaConnectionString() As String
            Get
                Return CType(Me("baseaguaConnectionString"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CAJAS.My.MySettings
            Get
                Return Global.CAJAS.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
